Feat/expdetail
etalab-ia/eg1 pull request #37
Opened 2024-12-04 15:49 UTC by AudreyCLEVY

objective: retrieve the results for each question for an id experiment: llm response, metrics, etc.

Ex : 
![Capture d’écran 2024-12-12 à 16 28 45](https://github.com/user-attachments/assets/11b173db-de17-4ee1-94eb-6a8c58a8b626)

![Capture d’écran 2024-12-12 à 16 27 53](https://github.com/user-attachments/assets/9874789a-4534-43ec-bb89-a5131ff76c0b)

2024-12-11 17:13 UTC, dtrckd requested changes
En dehors de mes review dans le code, il y a un truc qui me perturbe dans cette MR, par rapport au  : 

1.  Les modif apportées aux notebooks de référence. Je ne les comprends pas ? Il faut qu'on détermine un politique de stabilisation/evolution par rapport à l'édition des notebook. Ca va devenir pénible d'éditer les diff et gérer les conflit (car j'ai touché aux 3 notebooks de référence dans ma MR #36 ). En regardant j'ai l'impression que ce sont des edit lié à des test perso. Est-ce que c'est génant si tu checkout ces fichier pour annuler les modif, j'ai l'impression que c'est du test/debug de ton coté, qu'en penses-tu ?
2. J'ai un autre problème de stabilité/cohérence de l'API (mois génant que l'autre, dans le sens he peux passer outre dans cette MR eventuellemnt), vis-à-vis de la logique consistant à l'introduction de ExperimentWithDataset. En fait, a quelle besoin ca sert exactement, déjà ?

2024-12-11 17:13 UTC, dtrckd commented on api/schemas.py
> +    df: str | None = None # from_json
When a df can be None here ? I don"t see when that can happen. If you agree we can remove the `| None = None`

2024-12-11 17:13 UTC, dtrckd commented on api/schemas.py
> +    #created_at: datetime
I am going to merge main in this branch to resolve conflict (I will then uncomment this, I has I have added back created_at for answer in last version).

2024-12-11 17:13 UTC, dtrckd commented on api/schemas.py
> +    df: str | None = None
Why adding this one ?

2024-12-11 19:01 UTC, AudreyCLEVY commented
En fait sur les notebook je me suis faite la même remarque, faut que je checkout pour remettre tous els notebooks iso la main

2024-12-11 19:03 UTC, AudreyCLEVY commented
Le df je l'ajoute car j'ai besoin pour chaque question d'un dataset, d'avoir la réponse "true", la réponse du llm, les métriques associées.
Pourquoi :
1 / comprendre comment les notes se répartissent et zoomer
2/ pouvoir comparer 2 llms entre eux, réponse par réponse

2024-12-11 19:04 UTC, AudreyCLEVY commented on api/schemas.py
> +    df: str | None = None # from_json
il ne faudrait pas retirer à chaque fois qu'il y ait?

2024-12-11 19:06 UTC, AudreyCLEVY commented on api/schemas.py
> +    df: str | None = None
for adding df in experiment result

2024-12-11 19:16 UTC, dtrckd commented
> Le df je l'ajoute car j'ai besoin pour chaque question d'un dataset, d'avoir la réponse "true", la réponse du llm, les métriques associées. Pourquoi : 1 / comprendre comment les notes se répartissent et zoomer 2/ pouvoir comparer 2 llms entre eux, réponse par réponse

Le problème que j'ai avec cette approche, c'est que si on veux comparer 2 LLM entre eux réponse par réponse, cela veux dire qu'il on le même dataset en input, et donc le dataset, etant commun au deux il n'est pas utile, et contre-intuitif  devoir le télécharger plusieurs fois, chaque requête associé à un experiment.

Comme je l'évoquais, ce n'est pas urgent et je veux pas forcément bloquer la MR pour ca , mais pour moi la "bonne approche" de ton usecase serait la suivante. :
- un experiment set (i.e un scenario d'evluation)
- à partir de l'expset_id, récupérer **un fois** le dataset.
- à parti de l'expset_id, récupérer les Experiment with results (and wth answer if necessary). The num_line make the link with the dataset.
A discuter...

2024-12-11 19:17 UTC, dtrckd commented on api/schemas.py
> +    df: str | None = None # from_json
par exemple ou ?

2024-12-11 19:20 UTC, dtrckd commented on api/schemas.py
> +    df: str | None = None
Mais dans ce cas à quoi sert DatasetFull ?

2024-12-11 19:28 UTC, dtrckd commented
> * un experiment set (i.e un scenario d'evluation)
> 
> * à partir de l'expset_id, récupérer **un fois** le dataset.
> 
> * à parti de l'expset_id, récupérer les Experiment with results (and wth answer if necessary). The num_line make the link with the dataset.
>   A discuter...

En fait, le fait que le dataset est commun,dans ton scenario d’évaluation à toutes les expé, n'est pas quelque chose que l'API sait (même si elle pourrait le calculer facilement), ce qui signifie, dans mon approche, que l'utilisateur.rice devrait d'abord fetch les experiment, et en sachant que tout les datasets associé aux expérimentes sont en fait les mêm (puisque c'est l’utilisateur qui design l'expérience, pas l'API) il récupérerait le dataset par un call parallèle (à partir de la première expériencetypiquement....)....

2024-12-11 19:30 UTC, dtrckd commented
Par ailleurs, n'y a t'il pas un front, on une page dans l'UI qui illustre ton scenario d'utilisation ici, que tu caches quelque part ? :)

2024-12-11 19:49 UTC, dtrckd commented
On peut éventuellement procéder cette fois, mais en soit, lorsqu'on ajoute une feature à l'API , il faudra veiller, à terme, à y associé dans la PR, un ou plusieurs éléments de documentation/usage, c-a-d : 
- soit c'est un besoin interne à notre UI, et on associe la feat et l’élément de l'UI dans la PR
- soit c'est un besoin interne à un scenario d’évaluation, et on peut associé ca à un NB de démo et/ou un entré dans la documentation (qui n'existe pas encore, on attend un peu de stabiliser le truc je pense...)

Ca permet aussi plus facile de comprendre (pour la review en tout cas), si la feature est vraiment nécessaire ou si au contraire elle ajoute de la complexité non nécessaire à l'API (Ockam Razor, je suis toujours rasé de prés (c'est même pas vrai))

2024-12-12 13:57 UTC, AudreyCLEVY commented
@dtrckd voilà la MR "terminée";
C'ets une première version, mais je pense que ça peut être bien qu'elle soit poussée pour que les DS est déjà des vues du front;
je vais partir sur la partie Results; et réfléchir en // à la partie détail; qui n'est pas encore top à 100% mais ça serait top d'avoir le retour des utilisateurs pour converger vers leurs besoins

2024-12-12 14:21 UTC, dtrckd requested changes
Ok, juste deux point à revoir, après si t'es ok avec les modif, tu peux merge.

C'est dur de visualiser les modif d'UI juste avec le code, je regarderais l'effet sur la version déployé.

2024-12-12 14:21 UTC, dtrckd commented on api/schemas.py
> +            "readme": self.readme,
Tu peux effacer ca. C'est déjà dans **obj !
Les champs à rajouté sont des chmps qui necessite une computation sur le df lui meme (has_output, etc...)

2024-12-12 14:21 UTC, dtrckd commented on ui/demo_streamlit/views/datasets.py
> +                st.write(f"readme: {dataset['readme']}")
Comme Readme est optionnelle, mettre un test pour ne l'afficher que si présente, sinon il y aura "Readme: "  tout seul...

2024-12-12 14:41 UTC, AudreyCLEVY commented on ui/demo_streamlit/views/datasets.py
> +                st.write(f"readme: {dataset['readme']}")
en fait sur ce point ReadMe ne doit pas être optionnel, je pense qu'il faut vraiment qu'on le rende obligatoire
mais je ne sais pas comment "squizzer" le truc car j'ai enregistré des dataset en amont et c'est à nul;
Si tu as l'astuce je prends

2024-12-12 14:50 UTC, dtrckd commented on ui/demo_streamlit/views/datasets.py
> +                st.write(f"readme: {dataset['readme']}")
Ok, mais dans cas, il faut : 
1. virer la valeur par default et la l'option None dans le schema du Dataset.
2. Pour ce genre de cas, Il faut que editer le script de versionning à la main. Tu peux t'inspirer de celui-ci ou on rajouter le champs created_at obligatoire, partout il n'existait pas (il faut que tu mette une valeur par default donc !) :  a8816ddd6dfd_add_created_at_for_answers.py
3. test en local que ton script alembic fonctionne correctement

2024-12-12 14:51 UTC, dtrckd commented on ui/demo_streamlit/views/datasets.py
> +                st.write(f"readme: {dataset['readme']}")
Du coup, si on fait ca, pourquoi ne pas rendre le readme obligatoire poue les expset aussi ? (mais pas les expe unique par contre, trop contraignant...)

2024-12-12 15:30 UTC, AudreyCLEVY commented
@dtrckd  j'ai poussé la modif pour rendre obligatoire read me;
je te laisse me valider la mr

2024-12-12 15:53 UTC, dtrckd commented on api/alembic/versions/316562906577_readme_oblig_for_expset.py
> +    # ### end Alembic commands ###
il manque pas un truc dans ce fichier  ? tu l'a généré automatiquement ?

2024-12-12 19:07 UTC, AudreyCLEVY commented on api/alembic/versions/316562906577_readme_oblig_for_expset.py
> +    # ### end Alembic commands ###
ouep; tu penses qu'il y a un soucis?

2024-12-12 19:13 UTC, AudreyCLEVY commented on api/alembic/versions/316562906577_readme_oblig_for_expset.py
> +    # ### end Alembic commands ###
On n'a pas modifié la table, juste ses " contraintes", donc c'est logique qu'il n'y ait rien dans le fichier

2024-12-12 19:19 UTC, AudreyCLEVY commented on api/alembic/versions/316562906577_readme_oblig_for_expset.py
> +    # ### end Alembic commands ###
j'ai ajouter l'update

2024-12-14 01:25 UTC, dtrckd commented
Yop, j'ai résolu les conflict avec la branche main (fichier schema.py, ou j'ai bougé la config pydantic dans la classe mère EgBaseModel pour éviter les répétitions/confusion) + j'ai régénéré un fichier de versionning clean pour éviter les divergences de versionning (quand tu créé plusieurs script de version alembic qui parte du même point, ce qui était le cas, après il faut fusionner le tout, c'est feasible, mais chiant).

Merci, pour la contrib sur le front, sympa de commencer à avoir des éléments d'exploration des expé ;)

2024-12-14 01:25 UTC, merged