Feat/result
etalab-ia/eg1 pull request #62
Opened 2024-12-19 13:29 UTC by AudreyCLEVY

Add result in experiment set

First iteration - not perfect

for repeat:
<img width="1211" alt="Capture d’écran 2024-12-19 à 14 25 56" src="https://github.com/user-attachments/assets/e989ba7d-c0be-4a83-af0b-b55b10f7674c" />

for limit testing:
<img width="1209" alt="Capture d’écran 2024-12-19 à 14 27 07" src="https://github.com/user-attachments/assets/c0deb33a-0369-4982-8fb4-eae287f6a795" />

for rag metrics:
<img width="1185" alt="Capture d’écran 2024-12-19 à 14 27 50" src="https://github.com/user-attachments/assets/456c76f1-0d62-4c48-82b3-77eae53a157f" />

2024-12-20 13:32 UTC, dtrckd commented
@AudreyCLEVY il y a des conflit car la branche à divergé avec main suite à ma correction sur la manière de calculer les status des expset/expé.

J'ai intégré un dict pour gérer de manière plus fine les status des expériences et la notion de failure, il y a deux cas de failure distinct : 
- les output/answer failure
- les score/metrique failure

Ca se passe ici : https://github.com/etalab-ia/eg1/blob/main/ui/demo_streamlit/views/experiments_set.py#L61

Est-ce que tu veux regarder pour aligner ces modif dans ta branche @AudreyCLEVY  ?

2024-12-20 14:36 UTC, AudreyCLEVY commented
@dtrckd conflits resolved;

2024-12-20 20:54 UTC, dtrckd requested changes
A few questions, change requests and general remarks before merging.

Thank you @AudreyCLEVY

2024-12-20 20:54 UTC, dtrckd commented on ui/demo_streamlit/views/datasets.py
> -    # Main content
Why do you remove those comments ?

2024-12-20 20:54 UTC, dtrckd commented on ui/demo_streamlit/views/experiments_set.py
> +        st.write(expset["readme"] if expset["readme"] else "No README available.")
Can you use the same standard we already have in the function "display_experiments_set", which is : 

```
                st.markdown(exp_set.get("readme", "No description available"))
```

Or use yours, bu keep the same convention for thing that display the same thing to avoid having a confusing interface.

2024-12-20 20:54 UTC, dtrckd commented on ui/demo_streamlit/views/experiments_set.py
> +
Too hard to review, I will see the result on the front directly (But I am a bit afraid this not a enough a generalized piece of code...and hard to maintain though.)

2024-12-20 20:54 UTC, dtrckd commented on ui/demo_streamlit/views/experiments.py
> +    df_with_results, dataset_name, model_name = get_experiment_data(exp_id)
You are requesting the data twice, as there is already a call ("with_results")  in "process_experiment_results". You can rationalise that to make it easy to follow, and less agressive to the api (with_dataset also contains the result if I make no mistake!). The best approach, I think, is to keep that logics :
- get/prepare your data  at the top of your display function
- then pass it (the experiment full) to the function that are specific view on that data.

2024-12-20 23:45 UTC, dtrckd commented on ui/demo_streamlit/views/experiments_set.py
> +        st.write(expset["readme"] if expset["readme"] else "No README available.")
Je te l'ai résolu celle-ci en mergant main (résolvant un conflit!)

2024-12-30 07:32 UTC, AudreyCLEVY commented on ui/demo_streamlit/views/datasets.py
> -    # Main content
because it's in the name of the variable. I'll put it back if you prefer

2025-01-02 14:12 UTC, merged